name: test-github-actions 
on: [push] 
jobs: 
  build: 
  runs-on: ubuntu-latest 
  steps: 
  - name: Checkout repository 
  uses: actions/checkout@v2.3.3 
  - run: java -version 
  - run: javac -version 
  - run: mvn -v
  - run: echo "Build Project" 
  - run: mvn compile 
  - run: echo "Run JUnit4" 
  - run: mvn test 